# Generated by Django 4.1.7 on 2023-04-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defect_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('PNC', models.CharField(max_length=100)),
                ('Line', models.CharField(max_length=100)),
                ('location_lvl01', models.CharField(max_length=100)),
                ('Location_lvl02', models.CharField(max_length=100)),
                ('Defect', models.CharField(max_length=100)),
                ('Defect_cat', models.CharField(max_length=100)),
                ('Count_units', models.CharField(max_length=100)),
                ('Containment', models.CharField(max_length=200)),
                ('Corrective', models.CharField(max_length=200)),
                ('Operator', models.CharField(max_length=100)),
                ('Notified', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Defect_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defect_register.defect_weight')),
            ],
        ),
    ]
