# Generated by Django 4.1.7 on 2023-04-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect_register', '0002_rename_date_defect_created_at_defect_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='Defect_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defect_register.defect_cat'),
        ),
    ]
