# Generated by Django 4.1.7 on 2023-04-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_register', '0004_alter_defect_updated_at_alter_defect_cat_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='updated_at',
        ),
    ]
