# Generated by Django 4.1.7 on 2023-04-07 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('defect_register', '0005_remove_defect_created_at_remove_defect_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
